# kubeeye-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeeye
  namespace: kubeeye-system
  labels:
    app: kubeeye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeeye
  template:
    metadata:
      labels:
        app: kubeeye
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: kubeeye
        image: kubeeye:v2.0
        ports:
        - containerPort: 8501
        env:
        - name: KUBEEYE_DATA_DIR
          value: "/app/data"
        - name: KUBEEYE_GITOPS_REPO_NAME
          value: "kubeeye_rules"
        - name: KUBEEYE_GITOPS_REPO_URL
          value: "https://github.com/optical4eye/kubeeye-rules.git"
        - name: KUBEEYE_GITOPS_REPO_BRANCH
          value: "main"
        - name: KUBEEYE_GITOPS_REPO_USERNAME
          value: "optical4eye"
        - name: KUBEEYE_GITOPS_REPO_TOKEN
          value: ""
        - name: KUBEEYE_GITOPS_REPO_INSECURE
          value: "false"
        - name: KUBEEYE_GITOPS_REPO_DESCRIPTION
          value: "kubeeye repo rules"
        - name: KUBEYE_REPORT_RETENTION_DAYS
          value: '1'
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: kubeeye-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeeye-pvc
  namespace: kubeeye-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: kubeeye-service
  namespace: kubeeye-system
spec:
  selector:
    app: kubeeye
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30693
  type: NodePort
