---
# ExternalSecret
externalSecret:
  enabled: false
  clusterSecretStoreName: ""
  secrets:
  - secretName: "gitUser"
    vaultPath: "git/creds"
    vaultKey: "username"
  - secretName: "gitToken"
    vaultPath: "git/creds"
    vaultKey: "token"
  - secretName: "kubeeye-postgres-secret"
    vaultPath: "database/postgres"
    vaultKey: "password"

# Common configuration
common:
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
        type: RuntimeDefault

# Frontend configuration
frontend:
  replicaCount: 1
  image:
    repository: kubeeye-frontend
    tag: "v3.2"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  nodeSelector: {}
  resources:
    limits:
      memory: "1Gi"
      cpu: "500m"
    requests:
      memory: "1Gi"
      cpu: "500m"

# Backend configuration
backend:
  replicaCount: 1
  image:
    repository: kubeeye-backend
    tag: "v3.2"
    pullPolicy: IfNotPresent
  service:
    port: 8000
  nodeSelector: {}
  env:
    - name: KUBEEYE_GITOPS_REPO_NAME
      value: "kubeeye_rules"
    - name: KUBEEYE_GITOPS_REPO_URL
      value: "https://github.com/optical4eye/kubeeye-rules.git"
    - name: KUBEEYE_GITOPS_REPO_BRANCH
      value: "main"
    - name: KUBEEYE_GITOPS_REPO_USERNAME
      value: "optical4eye"
    - name: KUBEEYE_GITOPS_REPO_TOKEN
      value: ""
    - name: KUBEEYE_GITOPS_REPO_DESCRIPTION
      value: "kubeeye repo rules"
    - name: KUBEEYE_REPORT_RETENTION_DAYS
      value: '1'
    - name: GIT_SSL_NO_VERIFY
      value: '0'
    # - name: DB_HOST.  #in Deployment template
    - name: DB_USER
      value: "kubeeye"
    - name: DB_NAME
      value: "kubeeye"
    - name: DB_PASS
      value: "password"
  resources:
    limits:
      memory: "2Gi"
      cpu: "1000m"
    requests:
      memory: "2Gi"
      cpu: "1000m"

  persistence:
    enabled: false
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi

  LocalRules:
    - name: opa-host-network
      type: opa
    - name: node-disk-usage-simple
      type: node

# PostgreSQL configuration
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: 18-alpine
  auth:
    # existingSecret: ""
    # secretKeys:
    #   userPasswordKey: "user-password"
    username: "kubeeye"
    password: "password"
    database: "kubeeye"
  architecture: standalone
  primary:
    persistence:
      enabled: true
      size: 8Gi
    containerSecurityContext:
      readOnlyRootFilesystem: false
