{{- if eq .Values.externalSecret.enabled true }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "kubeeye.fullname" . }}-secrets
spec:
  data:
{{- range .Values.externalSecret.secrets }}
  - secretKey: {{ .secretName }}
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .vaultPath }}
      property: {{ .vaultKey }}
{{- end }}
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.clusterSecretStoreName }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: kubeeye-secret
    template:
      engineVersion: v2
      metadata: {}
      #type: kubernetes.io/tls
{{ end }}