---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeeye.fullname" . }}-pvc
  labels:
    {{- include "kubeeye.labels" . | nindent 4 }}
    app.kubernetes.io/component: persistence
    app.kubernetes.io/part-of: kubeeye
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | default "1Gi" }}
