apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeeye.fullname" . }}-svc
  labels:
  {{- include "kubeeye.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: kubeeye
  {{- include "kubeeye.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 }}
