[theme]
primaryColor = "#00a971"
backgroundColor = "#282f39"
secondaryBackgroundColor = "#222831"
textColor = "#F7F7F7"
font = "sans serif"

[server]
enableCORS = false

[client]
showSidebarNavigation = false
