[theme]
primaryColor = "#948979"
backgroundColor = "#848484ff"
secondaryBackgroundColor = "#222831"
textColor = "#F7F7F7"
font = "sans serif"

[server]
enableCORS = false

[client]
showSidebarNavigation = false